version: "3.9"
services:
  database:
    container_name: db-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elotus
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5432:5432"

  migrate:
    container_name: db-migrate
    image: migrate/migrate:4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elotus
    entrypoint: ['']
    command: ['echo', 'hello']
    volumes:
      - ./data/migration:/migration
    
